`File.absolute_path?` is available since Ruby 2.7
```
itamae local --node-yaml=/home/runner/work/itamae-plugin-recipe-rbenv/itamae-plugin-recipe-rbenv/spec/recipes/local/node.yml /home/runner/work/itamae-plugin-recipe-rbenv/itamae-plugin-recipe-rbenv/spec/recipes/local/install.rb
 INFO : Starting Itamae...
 INFO : Loading node data from /home/runner/work/itamae-plugin-recipe-rbenv/itamae-plugin-recipe-rbenv/spec/recipes/local/node.yml...
/home/runner/work/itamae-plugin-recipe-rbenv/itamae-plugin-recipe-rbenv/vendor/bundle/ruby/2.3.0/gems/itamae-1.14.1/lib/itamae/recipe.rb:168:in `eval': undefined method `absolute_path?' for File:Class (NoMethodError)
	from (eval):2:in `eval'
	from (eval):2:in `block in call'
	from (eval):1:in `instance_eval'
	from (eval):1:in `call'
```

https://github.com/itamae-plugins/itamae-plugin-recipe-rbenv/actions/runs/17357118435/job/49271767635?pr=47