Drop test on ubuntu-latest runner
`apt-get update` requires `sudo`

https://github.com/itamae-plugins/itamae-plugin-recipe-rbenv/actions/runs/17357366274/job/49272338326

```
 INFO :     execute[apt-get update] executed will change from 'false' to 'true'
ERROR :       stdout | Reading package lists...
ERROR :       stderr | E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
ERROR :       stderr | E: Unable to lock directory /var/lib/apt/lists/
ERROR :       Command `apt-get update` failed. (exit status: 100)
ERROR :     execute[apt-get update] Failed.
```

But `sudo bundle` is failed too...

https://github.com/itamae-plugins/itamae-plugin-recipe-rbenv/actions/runs/17357468872/job/49272575270

```
sudo: bundle: command not found
Error: Process completed with exit code 1.
```

Test on ubuntu-latest has been removed since it can be covered by test on docker